# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5faeeedad89408378dfd0463c99dff7530cbd7801ee1f8c6037784a53fe3042b0e0648ccdd2ac7e5dd5a508979904a9a0a9a74238c72102b30931fffa77b578e

test:
  secret_key_base: 370e71f93b0186678736ccce1f78fd261256f7b961b73444352e0818b721233f0972c41338248470272ea6cc6921b4917a6d4cfad4f6b325ce9703291268b73f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
